# action.yml
name: 'sf-package-version-update-action'
description: 'auto version increment sfdx-project json file'
inputs:
  ANCESTOR_ID: # id of input
    description: 'Id of ancestor package'
    required: false
  PACKAGE_NAME: # id of input
    description: 'Package name'
    required: false
outputs:
  SFDX_PROJECT: # id of output
    description: 'The sfdx-project.json file'
runs:
  using: 'node12'
  main: 'action.js'